# -*- coding: utf-8 -*-
"""py_base1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/167CGHqNqaoDWHk6awDaJcNt65DRLqZpQ

第一个函数

# 入门

# 新段落
"""

print("Hello, Python!")

"""Python注释
python中单行注释采用 # 开头。
"""

# 第一个注释
print("Hello, Python!")  # 第二个注释

"""python 中多行注释使用三个单引号(''')或三个双引号(''')。"""

'''
这是多行注释，使用单引号。
这是多行注释，使用单引号。
这是多行注释，使用单引号。
'''

"""
这是多行注释，使用双引号。
字符串
字符串是以单引号'或双引号"括起来的任意文本，比如'abc'，"xyz"等等。请注意，''或""本身只是一种表示方式，不是字符串的一部分，
因此，字符串'abc'只有a，b，c这3个字符。如果'本身也是一个字符，那就可以用""括起来，
比如"I'm OK"包含的字符是I，'，m，空格，O，K这6个字符。
如果字符串内部既包含'又包含"怎么办？可以用转义字符\来标识，比如：
"""

# 多行字符串
print('''line1
line2
line3''')

# 布尔值
'''
布尔值可以用and、or和not运算。

and运算是与运算，只有所有都为True，and运算结果才是True

布尔值经常用在条件判断中，比如：
'''
age = 19
if age >= 18:
    print('adult')
else:
    print('teenager')

#变量
'''
在Python中，等号=是赋值语句，可以把任意数据类型赋值给变量，同一个变量可以反复赋值，而且可以是不同类型的变量，例如
'''
a = 123 # a是整数
print(a)
a = 'ABC' # a变为字符串
print(a)

#常量
'''
所谓常量就是不能变的变量，比如常用的数学常数π就是一个常量。在Python中，通常用全部大写的变量名表示常量
'''
PI = 3.14159265359  

#练习 打印下面变量的值

n = 123
f = 456.789
s1 = 'Hello, world'
s2 = 'Hello, \'Adam\''
s3 = r'Hello, "Bart"'
s4 = r'''Hello,
Lisa!'''

print(s2)
print(f)
print(s3)
print(s4)